=== sk8tz/mcs/doctools/etc/monodoc.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root element -->
<!ELEMENT monodoc (class | delegate | enum | interface | struct)*>
<!ATTLIST monodoc
	language CDATA #REQUIRED
>

<!-- Type-level tags -->
<!ELEMENT class (summary, remarks?, (class | delegate | enum | interface | struct | constructor | event | field | method | operator | property)*, seealso*)>
<!ATTLIST class
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT delegate (summary, remarks?, param*, seealso*)>
<!ATTLIST delegate
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>
<!ELEMENT enum (summary, remarks?, member+)>
<!ATTLIST enum
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT interface (summary, remarks?, seealso*)>
<!ATTLIST interface
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT struct (summary, remarks?, (class | delegate | enum | interface | struct | constructor | event | field | method | operator | property)*, seealso*)>
<!ATTLIST struct
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!-- Member-level tags -->
<!ELEMENT constructor (summary, remarks?, param*, exception*, seealso*)>
<!ATTLIST constructor
	name CDATA #REQUIRED
>

<!ELEMENT event (summary, remarks?, data, seealso*)>
<!ATTLIST event
	name CDATA #REQUIRED
>

<!ELEMENT field (summary, remarks?, seealso*)>
<!ATTLIST field
	name CDATA #REQUIRED
>

<!ELEMENT method (summary, remarks?, param*, exception*, returns?, seealso*)>
<!ATTLIST method
	name CDATA #REQUIRED
>

<!ELEMENT operator (summary, remarks?, param*, exception*, returns?, seealso*)>
<!ATTLIST operator
	name CDATA #REQUIRED
>

<!ELEMENT property (summary, remarks?, value, exception*, seealso*)>
<!ATTLIST property
	name CDATA #REQUIRED
>

<!-- Member-info level tags -->
<!ELEMENT data (#PCDATA | c | example | list | para | see)*>

<!ELEMENT exception (#PCDATA | c | example | list | para | paramref | see)*>
<!ATTLIST exception
	cref CDATA #REQUIRED
>

<!ELEMENT member (#PCDATA | c | see)*>
<!ATTLIST member
	name CDATA #REQUIRED
>

<!ELEMENT param (#PCDATA | c | example | list | para | see)*>
<!ATTLIST param
	name CDATA #REQUIRED
>

<!ELEMENT remarks (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT returns (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT seealso EMPTY>
<!ATTLIST seealso
	cref CDATA #REQUIRED
>

<!ELEMENT summary (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT value (#PCDATA | c | example | list | para | paramref | see)*>

<!-- Formatting and presentation tags -->

<!ELEMENT c (#PCDATA)>

<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	lang CDATA #REQUIRED
>

<!ELEMENT description (#PCDATA | c | see)*>

<!ELEMENT example (#PCDATA | c | code | para | see)*>

<!ELEMENT item (term?, description)>

<!ELEMENT list (listheader?, item+)>
<!ATTLIST list
	type (bullet | number | table) #REQUIRED
>

<!ELEMENT listheader (term?, description)>

<!ELEMENT para (#PCDATA | c | example | list | paramref | see)*>

<!ELEMENT paramref EMPTY>
<!ATTLIST paramref
	name CDATA #REQUIRED
>

<!ELEMENT see (#PCDATA)>
<!ATTLIST see
	cref CDATA #REQUIRED
>

<!ELEMENT term (#PCDATA)>

=== sk8tz/mcs/docs/apidocs/System.CodeDom/CodeLiteralNamespace.xml
<?xml version="1.0"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="">
    <class name="System.CodeDom.CodeLiteralNamespace" assembly="System">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="CodeLiteralNamespace(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="value">TODO</param>
        </constructor>
        <property name="Value">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="LinePragma">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Net/IPAddress.xml
<?xml version="1.0"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Net.IPAddress" assembly="System">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="IPAddress(System.Int64)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="addr">TODO</param>
        </constructor>
        <field name="Any">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="Broadcast">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="Loopback">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="None">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <property name="Address">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="AddressFamily">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <method name="GetHashCode">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Equals(System.Object)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="other">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="ToString">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="HostToNetworkOrder(System.Int16)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="host">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="HostToNetworkOrder(System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="host">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="HostToNetworkOrder(System.Int64)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="host">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="NetworkToHostOrder(System.Int16)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="network">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="NetworkToHostOrder(System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="network">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="NetworkToHostOrder(System.Int64)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="network">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Parse(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="ip">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="IsLoopback(System.Net.IPAddress)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="addr">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System/Random.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Random" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="Random">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </constructor>
        <constructor name="Random(System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="Seed">TODO</param>
        </constructor>
        <method name="NextDouble">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="NextBytes(System.Byte[])">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="buffer">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Next(System.Int32, System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="minValue">TODO</param>
            <param name="maxValue">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Next(System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="maxValue">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Next">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/System.Net/IPEndPoint.xml
<?xml version="1.0"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="">
    <class name="System.Net.IPEndPoint" assembly="System">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="IPEndPoint(System.Net.IPAddress, System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="address">TODO</param>
            <param name="port">TODO</param>
        </constructor>
        <constructor name="IPEndPoint(System.Int64, System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="iaddr">TODO</param>
            <param name="port">TODO</param>
        </constructor>
        <field name="MaxPort">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="MinPort">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <property name="Address">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="AddressFamily">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Port">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <method name="Serialize">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Create(System.Net.SocketAddress)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="sockaddr">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="ToString">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Security.Cryptography/DSACryptoServiceProvider.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Security.Cryptography.DSACryptoServiceProvider" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="DSACryptoServiceProvider">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </constructor>
        <constructor name="DSACryptoServiceProvider(System.Security.Cryptography.CspParameters)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="parameters">TODO</param>
        </constructor>
        <constructor name="DSACryptoServiceProvider(System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="key_size">TODO</param>
        </constructor>
        <constructor name="DSACryptoServiceProvider(System.Int32, System.Security.Cryptography.CspParameters)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="key_size">TODO</param>
            <param name="parameters">TODO</param>
        </constructor>
        <property name="KeyExchangeAlgorithm">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="KeySize">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="LegalKeySizes">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="SignatureAlgorithm">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="PersistKeyInCsp">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <method name="VerifySignature(System.Byte[], System.Byte[])">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="hash">TODO</param>
            <param name="sig">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="ImportParameters(System.Security.Cryptography.DSAParameters)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="parameters">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="ExportParameters(System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="include">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="CreateSignature(System.Byte[])">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="rgb">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="ToXmlString(System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="includePrivateParameters">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="FromXmlString(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="xmlString">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="SignData(System.Byte[])">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="data">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="SignData(System.Byte[], System.Int32, System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="data">TODO</param>
            <param name="offset">TODO</param>
            <param name="count">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="SignData(System.IO.Stream)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="data">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="SignHash(System.Byte[], System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="hash">TODO</param>
            <param name="str">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="VerifyData(System.Byte[], System.Byte[])">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="data">TODO</param>
            <param name="sig">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System/UriFormatException.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.UriFormatException" assembly="System">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="UriFormatException">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </constructor>
        <constructor name="UriFormatException(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="message">TODO</param>
        </constructor>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Threading/Thread.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Threading.Thread" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="Thread(System.Threading.ThreadStart)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="start">TODO</param>
        </constructor>
        <property name="CurrentContext">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="CurrentPrincipal">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="CurrentThread">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="ApartmentState">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="CurrentCulture">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="CurrentUICulture">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="IsAlive">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="IsBackground">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Name">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Priority">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="ThreadState">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <method name="AllocateDataSlot">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="AllocateNamedDataSlot(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="name">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="FreeNamedDataSlot(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="name">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="GetData(System.LocalDataStoreSlot)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="slot">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="GetDomain">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="GetDomainID">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="GetNamedDataSlot(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="name">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="ResetAbort">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="SetData(System.LocalDataStoreSlot, System.Object)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="slot">TODO</param>
            <param name="data">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Sleep(System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="millisecondsTimeout">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Sleep(System.TimeSpan)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="timeout">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Abort">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Abort(System.Object)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="stateInfo">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Interrupt">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Join">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Join(System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="millisecondsTimeout">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Join(System.TimeSpan)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="timeout">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Resume">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Start">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Suspend">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>
