=== sk8tz/mcs/doctools/etc/monodoc.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root element -->
<!ELEMENT monodoc (class | delegate | enum | interface | struct)*>
<!ATTLIST monodoc
	language CDATA #REQUIRED
>

<!-- Type-level tags -->
<!ELEMENT class (summary, remarks?, (class | delegate | enum | interface | struct | constructor | event | field | method | operator | property)*, seealso*)>
<!ATTLIST class
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT delegate (summary, remarks?, param*, seealso*)>
<!ATTLIST delegate
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>
<!ELEMENT enum (summary, remarks?, member+)>
<!ATTLIST enum
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT interface (summary, remarks?, seealso*)>
<!ATTLIST interface
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT struct (summary, remarks?, (class | delegate | enum | interface | struct | constructor | event | field | method | operator | property)*, seealso*)>
<!ATTLIST struct
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!-- Member-level tags -->
<!ELEMENT constructor (summary, remarks?, param*, exception*, seealso*)>
<!ATTLIST constructor
	name CDATA #REQUIRED
>

<!ELEMENT event (summary, remarks?, data, seealso*)>
<!ATTLIST event
	name CDATA #REQUIRED
>

<!ELEMENT field (summary, remarks?, seealso*)>
<!ATTLIST field
	name CDATA #REQUIRED
>

<!ELEMENT method (summary, remarks?, param*, exception*, returns?, seealso*)>
<!ATTLIST method
	name CDATA #REQUIRED
>

<!ELEMENT operator (summary, remarks?, param*, exception*, returns?, seealso*)>
<!ATTLIST operator
	name CDATA #REQUIRED
>

<!ELEMENT property (summary, remarks?, value, exception*, seealso*)>
<!ATTLIST property
	name CDATA #REQUIRED
>

<!-- Member-info level tags -->
<!ELEMENT data (#PCDATA | c | example | list | para | see)*>

<!ELEMENT exception (#PCDATA | c | example | list | para | paramref | see)*>
<!ATTLIST exception
	cref CDATA #REQUIRED
>

<!ELEMENT member (#PCDATA | c | see)*>
<!ATTLIST member
	name CDATA #REQUIRED
>

<!ELEMENT param (#PCDATA | c | example | list | para | see)*>
<!ATTLIST param
	name CDATA #REQUIRED
>

<!ELEMENT remarks (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT returns (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT seealso EMPTY>
<!ATTLIST seealso
	cref CDATA #REQUIRED
>

<!ELEMENT summary (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT value (#PCDATA | c | example | list | para | paramref | see)*>

<!-- Formatting and presentation tags -->

<!ELEMENT c (#PCDATA)>

<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	lang CDATA #REQUIRED
>

<!ELEMENT description (#PCDATA | c | see)*>

<!ELEMENT example (#PCDATA | c | code | para | see)*>

<!ELEMENT item (term?, description)>

<!ELEMENT list (listheader?, item+)>
<!ATTLIST list
	type (bullet | number | table) #REQUIRED
>

<!ELEMENT listheader (term?, description)>

<!ELEMENT para (#PCDATA | c | example | list | paramref | see)*>

<!ELEMENT paramref EMPTY>
<!ATTLIST paramref
	name CDATA #REQUIRED
>

<!ELEMENT see (#PCDATA)>
<!ATTLIST see
	cref CDATA #REQUIRED
>

<!ELEMENT term (#PCDATA)>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Web.UI.WebControls/CommandEventArgs.xml
<?xml version="1.0"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Web.UI.WebControls.CommandEventArgs" assembly="System.Web">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="CommandEventArgs(System.Web.UI.WebControls.CommandEventArgs)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="e">TODO</param>
        </constructor>
        <constructor name="CommandEventArgs(System.String, System.Object)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="commandName">TODO</param>
            <param name="argument">TODO</param>
        </constructor>
        <property name="CommandName">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="CommandArgument">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Runtime.Serialization/SerializationBinder.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Runtime.Serialization.SerializationBinder" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <method name="BindToType(System.String, System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="assemblyName">TODO</param>
            <param name="typeName">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Security.Cryptography/DeriveBytes.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Security.Cryptography.DeriveBytes" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <method name="Reset">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="GetBytes(System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="cb">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Threading/Timer.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Threading.Timer" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="Timer(System.Threading.TimerCallback, System.Object, System.Int32, System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="dueTime">TODO</param>
            <param name="period">TODO</param>
        </constructor>
        <constructor name="Timer(System.Threading.TimerCallback, System.Object, System.Int64, System.Int64)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="dueTime">TODO</param>
            <param name="period">TODO</param>
        </constructor>
        <constructor name="Timer(System.Threading.TimerCallback, System.Object, System.TimeSpan, System.TimeSpan)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="dueTime">TODO</param>
            <param name="period">TODO</param>
        </constructor>
        <constructor name="Timer(System.Threading.TimerCallback, System.Object, System.UInt32, System.UInt32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="dueTime">TODO</param>
            <param name="period">TODO</param>
        </constructor>
        <method name="Dispose">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Change(System.Int32, System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="dueTime">TODO</param>
            <param name="period">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Change(System.Int64, System.Int64)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="dueTime">TODO</param>
            <param name="period">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Change(System.TimeSpan, System.TimeSpan)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="dueTime">TODO</param>
            <param name="period">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Change(System.UInt32, System.UInt32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="dueTime">TODO</param>
            <param name="period">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Dispose(System.Threading.WaitHandle)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="notifyObject">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Security/NamedPermissionSet.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Security.NamedPermissionSet" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="NamedPermissionSet(System.String, System.Security.PermissionSet)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="name">TODO</param>
            <param name="set">TODO</param>
        </constructor>
        <constructor name="NamedPermissionSet(System.String, System.Security.Permissions.PermissionState)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="name">TODO</param>
            <param name="state">TODO</param>
        </constructor>
        <constructor name="NamedPermissionSet(System.Security.NamedPermissionSet)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="set">TODO</param>
        </constructor>
        <constructor name="NamedPermissionSet(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="name">TODO</param>
        </constructor>
        <property name="Description">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Name">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <method name="ToXml">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="FromXml(System.Security.SecurityElement)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="e">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="Copy">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="Copy(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="name">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/System.Threading/ThreadExceptionEventArgs.xml
<?xml version="1.0"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="">
    <class name="System.Threading.ThreadExceptionEventArgs" assembly="System">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="ThreadExceptionEventArgs(System.Exception)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="t">TODO</param>
        </constructor>
        <property name="Exception">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Runtime.InteropServices/DllImportAttribute.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Runtime.InteropServices.DllImportAttribute" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="DllImportAttribute(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="dllName">TODO</param>
        </constructor>
        <field name="CallingConvention">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="CharSet">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="EntryPoint">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="ExactSpelling">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="PreserveSig">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <field name="SetLastError">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </field>
        <property name="Value">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Xml/XmlCharacterData.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Xml.XmlCharacterData" assembly="System.Xml">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <property name="Data">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="InnerText">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Length">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Value">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <method name="Substring(System.Int32, System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="offset">TODO</param>
            <param name="count">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="ReplaceData(System.Int32, System.Int32, System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="offset">TODO</param>
            <param name="count">TODO</param>
            <param name="strData">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="InsertData(System.Int32, System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="offset">TODO</param>
            <param name="strData">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="DeleteData(System.Int32, System.Int32)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="offset">TODO</param>
            <param name="count">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="AppendData(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="strData">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>
