=== sk8tz/mcs/doctools/etc/monodoc.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root element -->
<!ELEMENT monodoc (class | delegate | enum | interface | struct)*>
<!ATTLIST monodoc
	language CDATA #REQUIRED
>

<!-- Type-level tags -->
<!ELEMENT class (summary, remarks?, (class | delegate | enum | interface | struct | constructor | event | field | method | operator | property)*, seealso*)>
<!ATTLIST class
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT delegate (summary, remarks?, param*, seealso*)>
<!ATTLIST delegate
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>
<!ELEMENT enum (summary, remarks?, member+)>
<!ATTLIST enum
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT interface (summary, remarks?, seealso*)>
<!ATTLIST interface
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!ELEMENT struct (summary, remarks?, (class | delegate | enum | interface | struct | constructor | event | field | method | operator | property)*, seealso*)>
<!ATTLIST struct
	name CDATA #REQUIRED
	assembly CDATA #IMPLIED
>

<!-- Member-level tags -->
<!ELEMENT constructor (summary, remarks?, param*, exception*, seealso*)>
<!ATTLIST constructor
	name CDATA #REQUIRED
>

<!ELEMENT event (summary, remarks?, data, seealso*)>
<!ATTLIST event
	name CDATA #REQUIRED
>

<!ELEMENT field (summary, remarks?, seealso*)>
<!ATTLIST field
	name CDATA #REQUIRED
>

<!ELEMENT method (summary, remarks?, param*, exception*, returns?, seealso*)>
<!ATTLIST method
	name CDATA #REQUIRED
>

<!ELEMENT operator (summary, remarks?, param*, exception*, returns?, seealso*)>
<!ATTLIST operator
	name CDATA #REQUIRED
>

<!ELEMENT property (summary, remarks?, value, exception*, seealso*)>
<!ATTLIST property
	name CDATA #REQUIRED
>

<!-- Member-info level tags -->
<!ELEMENT data (#PCDATA | c | example | list | para | see)*>

<!ELEMENT exception (#PCDATA | c | example | list | para | paramref | see)*>
<!ATTLIST exception
	cref CDATA #REQUIRED
>

<!ELEMENT member (#PCDATA | c | see)*>
<!ATTLIST member
	name CDATA #REQUIRED
>

<!ELEMENT param (#PCDATA | c | example | list | para | see)*>
<!ATTLIST param
	name CDATA #REQUIRED
>

<!ELEMENT remarks (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT returns (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT seealso EMPTY>
<!ATTLIST seealso
	cref CDATA #REQUIRED
>

<!ELEMENT summary (#PCDATA | c | example | list | para | paramref | see)*>

<!ELEMENT value (#PCDATA | c | example | list | para | paramref | see)*>

<!-- Formatting and presentation tags -->

<!ELEMENT c (#PCDATA)>

<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	lang CDATA #REQUIRED
>

<!ELEMENT description (#PCDATA | c | see)*>

<!ELEMENT example (#PCDATA | c | code | para | see)*>

<!ELEMENT item (term?, description)>

<!ELEMENT list (listheader?, item+)>
<!ATTLIST list
	type (bullet | number | table) #REQUIRED
>

<!ELEMENT listheader (term?, description)>

<!ELEMENT para (#PCDATA | c | example | list | paramref | see)*>

<!ELEMENT paramref EMPTY>
<!ATTLIST paramref
	name CDATA #REQUIRED
>

<!ELEMENT see (#PCDATA)>
<!ATTLIST see
	cref CDATA #REQUIRED
>

<!ELEMENT term (#PCDATA)>

=== sk8tz/mcs/docs/apidocs/xml/en/System/MarshalByRefObject.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.MarshalByRefObject" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <method name="InitializeLifetimeService">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="GetLifetimeService">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
        <method name="CreateObjRef(System.Type)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="type">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Xml.Schema/XmlSchemaContentModel.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Xml.Schema.XmlSchemaContentModel" assembly="System.Xml">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <property name="Content">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Security.Cryptography/DSASignatureFormatter.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Security.Cryptography.DSASignatureFormatter" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="DSASignatureFormatter">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </constructor>
        <constructor name="DSASignatureFormatter(System.Security.Cryptography.AsymmetricAlgorithm)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="key">TODO</param>
        </constructor>
        <method name="CreateSignature(System.Byte[])">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="rgbHash">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="SetKey(System.Security.Cryptography.AsymmetricAlgorithm)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="key">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="SetHashAlgorithm(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="strName">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Reflection/ParameterInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Reflection.ParameterInfo" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <property name="ParameterType">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Attributes">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="DefaultValue">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="IsIn">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="IsLcid">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="IsOptional">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="IsOut">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="IsRetval">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Member">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Name">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Position">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <method name="IsDefined(System.Type, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="attributeType">TODO</param>
            <param name="inherit">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="GetCustomAttributes(System.Type, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="attributeType">TODO</param>
            <param name="inherit">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="GetCustomAttributes(System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="inherit">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Threading/ThreadPool.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Threading.ThreadPool" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <method name="BindHandle(System.IntPtr)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="osHandle">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="QueueUserWorkItem(System.Threading.WaitCallback)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="callback">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="QueueUserWorkItem(System.Threading.WaitCallback, System.Object)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="RegisterWaitForSingleObject(System.Threading.WaitHandle, System.Threading.WaitOrTimerCallback, System.Object, System.Int32, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="waitObject">TODO</param>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="millisecondsTimeOutInterval">TODO</param>
            <param name="executeOnlyOnce">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="RegisterWaitForSingleObject(System.Threading.WaitHandle, System.Threading.WaitOrTimerCallback, System.Object, System.Int64, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="waitObject">TODO</param>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="millisecondsTimeOutInterval">TODO</param>
            <param name="executeOnlyOnce">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="RegisterWaitForSingleObject(System.Threading.WaitHandle, System.Threading.WaitOrTimerCallback, System.Object, System.TimeSpan, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="waitObject">TODO</param>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="timeout">TODO</param>
            <param name="executeOnlyOnce">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="RegisterWaitForSingleObject(System.Threading.WaitHandle, System.Threading.WaitOrTimerCallback, System.Object, System.UInt32, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="waitObject">TODO</param>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="millisecondsTimeOutInterval">TODO</param>
            <param name="executeOnlyOnce">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="UnsafeQueueUserWorkItem(System.Threading.WaitCallback, System.Object)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="UnsafeRegisterWaitForSingleObject(System.Threading.WaitHandle, System.Threading.WaitOrTimerCallback, System.Object, System.Int32, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="waitObject">TODO</param>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="millisecondsTimeOutInterval">TODO</param>
            <param name="executeOnlyOnce">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="UnsafeRegisterWaitForSingleObject(System.Threading.WaitHandle, System.Threading.WaitOrTimerCallback, System.Object, System.Int64, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="waitObject">TODO</param>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="millisecondsTimeOutInterval">TODO</param>
            <param name="executeOnlyOnce">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="UnsafeRegisterWaitForSingleObject(System.Threading.WaitHandle, System.Threading.WaitOrTimerCallback, System.Object, System.TimeSpan, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="waitObject">TODO</param>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="timeout">TODO</param>
            <param name="executeOnlyOnce">TODO</param>
            <returns>TODO</returns>
        </method>
        <method name="UnsafeRegisterWaitForSingleObject(System.Threading.WaitHandle, System.Threading.WaitOrTimerCallback, System.Object, System.UInt32, System.Boolean)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="waitObject">TODO</param>
            <param name="callback">TODO</param>
            <param name="state">TODO</param>
            <param name="millisecondsTimeOutInterval">TODO</param>
            <param name="executeOnlyOnce">TODO</param>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Security.Policy/Evidence.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Security.Policy.Evidence" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="Evidence">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
        </constructor>
        <method name="GetHostEnumerator">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Xml.XPath/XPathScanner.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Xml.XPath.XPathScanner" assembly="System.Xml">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="XPathScanner(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="xpath">TODO</param>
        </constructor>
        <property name="TokenType">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <property name="Value">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
        <method name="Scan">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <returns>TODO</returns>
        </method>
    </class>
</monodoc>

=== sk8tz/mcs/docs/apidocs/xml/en/System.Reflection/AssemblyKeyNameAttribute.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monodoc SYSTEM "http://www.go-mono.org/monodoc.dtd">
<monodoc language="en">
    <class name="System.Reflection.AssemblyKeyNameAttribute" assembly="corlib">
        <summary>TODO</summary>
        <remarks>TODO</remarks>
        <constructor name="AssemblyKeyNameAttribute(System.String)">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <param name="keyName">TODO</param>
        </constructor>
        <property name="KeyName">
            <summary>TODO</summary>
            <remarks>TODO</remarks>
            <value>TODO</value>
        </property>
    </class>
</monodoc>
